# Generated by Django 4.2 on 2024-04-22 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("file", models.FileField(upload_to="movies")),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("description", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "type",
                    models.CharField(
                        choices=[("seasonal", "Seasonal"), ("single", "Single")],
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(upload_to="covers")),
                (
                    "age_limit",
                    models.CharField(
                        choices=[("All", "All"), ("Kids", "Kids")], max_length=10
                    ),
                ),
                ("video", models.ManyToManyField(to="api.video")),
            ],
        ),
    ]
