# Generated by Django 4.2 on 2024-05-28 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='uuid',
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('action', 'Action'), ('fantasy', 'Fantasy'), ('adventure', 'Adventure')], max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='proimage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.movie'),
        ),
    ]
