# Generated by Django 4.2 on 2024-05-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proimage_remove_movie_age_limit_remove_movie_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
