# Generated by Django 4.2 on 2024-05-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='cover_image',
        ),
    ]
