# Generated by Django 4.2 on 2024-05-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=models.FileField(null=True, upload_to='movies'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
