# Generated by Django 4.2 on 2024-05-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_movie_video_movie_trailer_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='video_link',
            new_name='movie_link',
        ),
    ]
