# Generated by Django 4.2 on 2024-05-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_movie_trailer_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_video',
            field=models.FileField(null=True, upload_to='movies'),
        ),
    ]
